// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Home' | 'Landing' | 'Login' | 'Users/Index' | 'Users/New' | 'Users/Show' | 'dashboard/Dashboard' | 'dashboard/NewProject' | 'dashboard/ProjectDetail' | 'layouts/AppLayout' | 'layouts/AppShell' | 'layouts/DocsLayout' | 'ui/badge' | 'ui/button' | 'ui/card' | 'ui/input'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Home': unknown
    'Landing': unknown
    'Login': unknown
    'Users/Index': unknown
    'Users/New': unknown
    'Users/Show': unknown
    'dashboard/Dashboard': unknown
    'dashboard/NewProject': unknown
    'dashboard/ProjectDetail': unknown
    'layouts/AppLayout': unknown
    'layouts/AppShell': unknown
    'layouts/DocsLayout': unknown
    'ui/badge': unknown
    'ui/button': unknown
    'ui/card': unknown
    'ui/input': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
