// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Landing' | 'Login' | 'dashboard/Dashboard' | 'dashboard/NewProject' | 'dashboard/ProjectDetail' | 'dashboard/ProjectSettings' | 'layouts/AppShell' | 'layouts/DocsLayout'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Landing': unknown
    'Login': unknown
    'dashboard/Dashboard': unknown
    'dashboard/NewProject': unknown
    'dashboard/ProjectDetail': unknown
    'dashboard/ProjectSettings': unknown
    'layouts/AppShell': unknown
    'layouts/DocsLayout': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
